server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: optional:file:../.env[.properties]
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/users/**
        - id: hotel
          uri: lb://hotel
          predicates:
            - Path=/api/hotels/**,/api/bookings/**,/api/bookingstatushistorys/**
        - id: minio
          uri: lb://minio
          predicates:
            - Path=/api/images/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET}