CREATE ROLE ai_reader LOGIN PASSWORD 'AiRead7kQ2xPm9Lw';
GRANT CONNECT ON DATABASE booking TO ai_reader;
GRANT USAGE ON SCHEMA public TO ai_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ai_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ai_reader;